name: False positive

description: Report a false positive







body:

  - type: markdown

    attributes:

      value: |

        ## Thanks for reporting this false positive.

  - type: input

    id: contact

    attributes:

      label: Username

      description: Please provide your Wikimodels username.

      placeholder: ex. John

    validations:

      required: true

  - type: dropdown

    id: tp

    attributes:

      label: Are you vandalising Wikimodels?


      description: If so, risk getting blocked from editing.
      
      options:
      
        - No
        - Yes (if so, we are angry. We are wiki demons. 😈)

    validations:

      required: true

  - type: dropdown

    id: version
  
    attributes:
      label: What bot unundid your changes?
      description: It must be the proper legit AV-Bot!
      options:
 


        - The Anti-Vandalism Bot

        - Another bot, or an illegit version of the AV-Bot (will not handle)

    validations:

      required: true

  - type: dropdown

    id: browsers

    attributes:

      label: What level of AV warning did you get?

      multiple: false

      options:

        - 1 - Notice

        - 2 - Caution

        - 3 - Warning

        - 4 - Final warning

  - type: textarea

    id: links

    attributes:

      label: Links to revisions

      description: Please copy and paste any links to the improper reverts.

      render: markdown




  



